# Project: Cipher
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o Function.o
LINKOBJ  = main.o Function.o
LIBS     = -L"E:/code/IDEdevc/Dev-Cpp/MinGW64/lib" -L"E:/code/IDEdevc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g -g3
INCS     = -I"E:/code/IDEdevc/Dev-Cpp/MinGW64/include" -I"E:/code/IDEdevc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/code/IDEdevc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/code/IDEdevc/Dev-Cpp/MinGW64/include" -I"E:/code/IDEdevc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/code/IDEdevc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/code/IDEdevc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Cipher.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11 -g3 -g -DRAVENCLAW
CFLAGS   = $(INCS) -std=gnu++11 -g3 -g -DRAVENCLAW
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Function.o: Function.cpp
	$(CPP) -c Function.cpp -o Function.o $(CXXFLAGS)
